bankAccount Edward = new bankAccount();
bankAccount Taylor = new bankAccount();

Edward.deposit(10); //Edward balance is now: 10
Taylor.deposit(5); //Taylor balance is now: 5
Edward.deposit(10); //Edward balance is now: 20
Taylor.deposit(95); //Taylor balance is now: 100

Edward.contributeToFund(50); // Total bank reserve fund is now: 50
Taylor.contributeToFund(100); // Total bank reserve fund is now: 150
